version: '2'
services:
  train:
    build: .
    image: dream-training
    command: "bash"
    volumes:
      - .:/root/neuralNet
    volumes_from:
      - train-data
  train-data:
    image: busybox
    volumes:
      - /root/neuralNet/training_output

  sample:
    build: .
    image: dream-sampling
    command: "th sample.lua -checkpoint \"/root/neuralNet/obama-rnn/obama_rnn.t7\" -length 2000 -gpu -1 -temperature .9 -start_text \"Thankyou.\""
    volumes:
      - .:/root/neuralNet
    volumes_from:
      - sample-data

  sample-data:
    image: busybox
    volumes:
      - /root/neuralNet/sample-out/